services:
    api:
        build: .
        container_name: slotbooking-api
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=postgres
            - REDIS_HOST=redis
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped

    postgres:
        image: postgres:16-alpine
        container_name: slotbooking-postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
                ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: slotbooking-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    celery-worker:
        build: .
        container_name: slotbooking-celery-worker

        command: >
            celery
            -A app.core.celery_app
            worker
            --loglevel=info

        volumes:
            - .:/app

        env_file:
            - .env

        environment:
            POSTGRES_HOST: postgres
            REDIS_HOST: redis

        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped

    celery-beat:
        build: .
        container_name: slotbooking-celery-beat

        command: >
            celery
            -A app.core.celery_app
            beat
            --loglevel=info

        volumes:
            - .:/app

        env_file:
            - .env

        environment:
            POSTGRES_HOST: postgres
            REDIS_HOST: redis

        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped

volumes:
    postgres_data:
    redis_data: