"""add tenant_id to providers, slots, bookings

Revision ID: 6afd5b8d604d
Revises: 3d714ff9004f
Create Date: 2026-07-29 00:39:01.522289

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afd5b8d604d'
down_revision: Union[str, Sequence[str], None] = '3d714ff9004f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# A single placeholder tenant ID for backfilling pre-existing dev/test
# rows created before multi-tenancy existed. These rows have no real
# tenant to attribute to — this value exists purely so NOT NULL can be
# applied. Never reuse this UUID as a real tenant later.
LEGACY_TENANT_ID = uuid.UUID("00000000-0000-0000-0000-000000000000")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ('bookings', 'providers', 'slots'):
        op.add_column(table, sa.Column('tenant_id', sa.Uuid(), nullable=True))
        # backfill every existing row with the placeholder, so
        # no row is left NULL before we tighten the constraint.
        op.execute(
            f"UPDATE {table} SET tenant_id = '{LEGACY_TENANT_ID}' WHERE tenant_id IS NULL"
        )
        op.alter_column(table, "tenant_id", nullable=False)
        op.create_index(f'ix_{table}_tenant_id', table, ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("providers", "slots", "bookings"):
        op.drop_index(f"ix_{table}_tenant_id", table_name=table)
        op.drop_column(table, "tenant_id")
    # ### end Alembic commands ###
